  product-db:
    image: mysql:8
    container_name: product-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: product_db
    ports:
      - '3307:3306'
    volumes:
      - product_data:/var/lib/mysql

  product-service:
    build: ./product-service
    container_name: product-service
    restart: always
    ports:
      - '3002:3002'
    depends_on:
      - product-db
    environment:
      PORT: 3002
      DB_HOST: product-db
      DB_USER: root
      DB_PASS: yourpassword
      DB_NAME: product_db
      JWT_SECRET: your_jwt_secret

